language: python
python:
  - "3.7"
cache: pip
before_install:
  - sudo apt-get install -y unixodbc-dev
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover --start-directory spinetoolbox